@startuml

skinparam componentStyle uml2

package "'Instrumento' Aggregate" <<Rectangle>> {
	class Instrumento <<(A,#fffab8) Aggregate Root>> {
		String nome
		String tipo
		Date ultimaEsterilizacao
		Date validadeEsterilizacao
		Boolean ativo
		InstrumentoId instrumentoId
		StatusEsterilizacao status
	}
	class InstrumentoId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	enum StatusEsterilizacao {
		ESTERILIZADO
		PENDENTE_ESTERILIZACAO
		VENCIDO
	}
	class InstrumentoPendenteEsterilizacao <<(E,#ff9f4b) Domain Event>> {
		Long procedimentoId
		InstrumentoId instrumentoId
	}
	class EsterilizacaoVencida <<(E,#ff9f4b) Domain Event>> {
		InstrumentoId instrumentoId
	}
}
package "'Esterilizacao' Aggregate" <<Rectangle>> {
	class CicloEsterilizacao <<(A,#fffab8) Aggregate Root>> {
		Long instrumentoId
		Date data
		String responsavel
		Date validade
		EsterilizacaoId esterilizacaoId
		MetodoEsterilizacao metodo
	}
	class EsterilizacaoId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	enum MetodoEsterilizacao {
		AUTOCLAVE
		ESTUFA
		GLUTARALDEIDO
	}
	class EsterilizacaoRegistrada <<(E,#ff9f4b) Domain Event>> {
		Long instrumentoId
		Date validade
		EsterilizacaoId esterilizacaoId
	}
}
Instrumento --> StatusEsterilizacao : status
InstrumentoPendenteEsterilizacao --> InstrumentoId : instrumentoId
EsterilizacaoVencida --> InstrumentoId : instrumentoId
CicloEsterilizacao --> MetodoEsterilizacao : metodo
EsterilizacaoRegistrada --> EsterilizacaoId : esterilizacaoId
CicloEsterilizacao --> EsterilizacaoId : esterilizacaoId
Instrumento --> InstrumentoId : instrumentoId
legend left
  This bounded context implements the subdomain 'InstrumentalDomain'.
end legend


@enduml
