@startuml

skinparam componentStyle uml2

package "'Comissao' Aggregate" <<Rectangle>> {
	class Comissao <<(A,#fffab8) Aggregate Root>> {
		Long especialistaId
		Long procedimentoId
		Long pagamentoId
		BigDecimal valorCalculado
		Date dataCalculo
		Date dataLiberacao
		ComissaoId comissaoId
		StatusComissao status
	}
	class ComissaoId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	enum StatusComissao {
		PENDENTE
		LIBERADA
		REPASSADA
	}
	class ComissaoCalculada <<(E,#ff9f4b) Domain Event>> {
		Long especialistaId
		Long procedimentoId
		BigDecimal valor
		ComissaoId comissaoId
	}
	class ComissaoLiberada <<(E,#ff9f4b) Domain Event>> {
		Long especialistaId
		ComissaoId comissaoId
	}
}
ComissaoCalculada --> ComissaoId : comissaoId
Comissao --> ComissaoId : comissaoId
Comissao --> StatusComissao : status
ComissaoLiberada --> ComissaoId : comissaoId


@enduml
