@startuml

skinparam componentStyle uml2

package "'Pagamento' Aggregate" <<Rectangle>> {
	class Pagamento <<(A,#fffab8) Aggregate Root>> {
		Long orcamentoId
		Long pacienteId
		BigDecimal valorTotal
		Date dataRegistro
		PagamentoId pagamentoId
		TipoPagamento tipo
	}
	class Parcela <<(E,DarkSeaGreen) Entity>> {
		Integer numero
		BigDecimal valor
		Date dataVencimento
		Date dataPagamento
		ParcelaId parcelaId
		StatusParcela status
	}
	class PagamentoId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	class ParcelaId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	enum TipoPagamento {
		A_VISTA
		PARCELADO
	}
	enum StatusParcela {
		PENDENTE
		LIQUIDADA
		INADIMPLENTE
	}
	class ParcelaLiquidada <<(E,#ff9f4b) Domain Event>> {
		Long pacienteId
		BigDecimal valor
		Date dataPagamento
		ParcelaId parcelaId
		PagamentoId pagamentoId
	}
	class ParcelaVencidaSemPagamento <<(E,#ff9f4b) Domain Event>> {
		Long pacienteId
		Date dataVencimento
		ParcelaId parcelaId
		PagamentoId pagamentoId
	}
}
ParcelaLiquidada --> ParcelaId : parcelaId
ParcelaVencidaSemPagamento --> PagamentoId : pagamentoId
Parcela --> StatusParcela : status
Pagamento --> PagamentoId : pagamentoId
ParcelaLiquidada --> PagamentoId : pagamentoId
ParcelaVencidaSemPagamento --> ParcelaId : parcelaId
Pagamento --> TipoPagamento : tipo
Parcela --> ParcelaId : parcelaId


@enduml
