@startuml

skinparam componentStyle uml2

package "'Equipamento' Aggregate" <<Rectangle>> {
	class Equipamento <<(A,#fffab8) Aggregate Root>> {
		String nome
		String modelo
		String fabricante
		Integer periodicidadeManutencaoDias
		Date ultimaManutencao
		Date proximaManutencao
		Boolean ativo
		EquipamentoId equipamentoId
		StatusEquipamento status
	}
	class EquipamentoId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	enum StatusEquipamento {
		DISPONIVEL
		EM_MANUTENCAO
		INDISPONIVEL
	}
	class AlertaManutencaoEmitido <<(E,#ff9f4b) Domain Event>> {
		String nomeEquipamento
		Date proximaManutencao
		Integer diasRestantes
		EquipamentoId equipamentoId
	}
	class EquipamentoIndisponivel <<(E,#ff9f4b) Domain Event>> {
		String motivo
		EquipamentoId equipamentoId
	}
	class EquipamentoDisponivel <<(E,#ff9f4b) Domain Event>> {
		EquipamentoId equipamentoId
	}
}
Equipamento --> StatusEquipamento : status
EquipamentoDisponivel --> EquipamentoId : equipamentoId
EquipamentoIndisponivel --> EquipamentoId : equipamentoId
Equipamento --> EquipamentoId : equipamentoId
AlertaManutencaoEmitido --> EquipamentoId : equipamentoId


@enduml
