@startuml

skinparam componentStyle uml2

package "'Especialista' Aggregate" <<Rectangle>> {
	class Especialista <<(A,#fffab8) Aggregate Root>> {
		String nome
		String especialidade
		String registro
		Boolean ativo
		EspecialistaId especialistaId
	}
	class EspecialistaId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	class RegraComissao <<(V,DarkSeaGreen) Value Object>> {
		Long procedimentoId
		String descricaoProcedimento
		BigDecimal valor
		TipoComissao tipo
	}
	enum TipoComissao {
		PERCENTUAL
		VALOR_FIXO
	}
	class EspecialistaCadastrado <<(E,#ff9f4b) Domain Event>> {
		String nome
		String especialidade
		EspecialistaId especialistaId
	}
}
Especialista --> EspecialistaId : especialistaId
EspecialistaCadastrado --> EspecialistaId : especialistaId
RegraComissao --> TipoComissao : tipo


@enduml
