@startuml

skinparam componentStyle uml2

package "'Inadimplencia' Aggregate" <<Rectangle>> {
	class RegistroInadimplencia <<(A,#fffab8) Aggregate Root>> {
		Long pacienteId
		Long parcelaId
		Date dataVencimento
		Boolean bloqueioAtivo
		String autorizacaoDesbloqueio
		String responsavelAutorizacao
		InadimplenciaId inadimplenciaId
	}
	class InadimplenciaId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	class RegistroCobranca <<(V,DarkSeaGreen) Value Object>> {
		Date data
		String responsavel
		String resultado
		String observacao
	}
	class BloqueioAgendamentoAtivado <<(E,#ff9f4b) Domain Event>> {
		Long pacienteId
		InadimplenciaId inadimplenciaId
	}
	class BloqueioAgendamentoRemovido <<(E,#ff9f4b) Domain Event>> {
		Long pacienteId
		String autorizacao
		InadimplenciaId inadimplenciaId
	}
	class InadimplenciaRegularizada <<(E,#ff9f4b) Domain Event>> {
		Long pacienteId
		Date dataQuitacao
		InadimplenciaId inadimplenciaId
	}
}
RegistroInadimplencia --> InadimplenciaId : inadimplenciaId
BloqueioAgendamentoAtivado --> InadimplenciaId : inadimplenciaId
BloqueioAgendamentoRemovido --> InadimplenciaId : inadimplenciaId
InadimplenciaRegularizada --> InadimplenciaId : inadimplenciaId


@enduml
