@startuml

skinparam componentStyle uml2

package "'LancamentoFinanceiro' Aggregate" <<Rectangle>> {
	class LancamentoFinanceiro <<(A,#fffab8) Aggregate Root>> {
		BigDecimal valor
		Date data
		String categoria
		String descricao
		String justificativa
		Boolean geradoAutomaticamente
		String origemReferencia
		LancamentoId lancamentoId
		TipoLancamento tipo
	}
	class LancamentoId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	enum TipoLancamento {
		ENTRADA
		SAIDA
	}
	class EntradaRegistrada <<(E,#ff9f4b) Domain Event>> {
		BigDecimal valor
		Date data
		String origem
		LancamentoId lancamentoId
	}
	class SaidaRegistrada <<(E,#ff9f4b) Domain Event>> {
		BigDecimal valor
		String categoria
		LancamentoId lancamentoId
	}
}
SaidaRegistrada --> LancamentoId : lancamentoId
LancamentoFinanceiro --> TipoLancamento : tipo
EntradaRegistrada --> LancamentoId : lancamentoId
LancamentoFinanceiro --> LancamentoId : lancamentoId


@enduml
