@startuml

skinparam componentStyle uml2

package "'Especialista' Aggregate" <<Rectangle>> {
	class Especialista <<(A,#fffab8) Aggregate Root>> {
		String nome
		String especialidade
		String registro
		Boolean ativo
		EspecialistaId especialistaId
	}
	class EspecialistaId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	class RegraComissao <<(V,DarkSeaGreen) Value Object>> {
		Long procedimentoId
		String descricaoProcedimento
		BigDecimal valor
		TipoComissao tipo
	}
	enum TipoComissao {
		PERCENTUAL
		VALOR_FIXO
	}
	class EspecialistaCadastrado <<(E,#ff9f4b) Domain Event>> {
		String nome
		String especialidade
		EspecialistaId especialistaId
	}
}
package "'Comissao' Aggregate" <<Rectangle>> {
	class Comissao <<(A,#fffab8) Aggregate Root>> {
		Long especialistaId
		Long procedimentoId
		Long pagamentoId
		BigDecimal valorCalculado
		Date dataCalculo
		Date dataLiberacao
		ComissaoId comissaoId
		StatusComissao status
	}
	class ComissaoId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	enum StatusComissao {
		PENDENTE
		LIBERADA
		REPASSADA
	}
	class ComissaoCalculada <<(E,#ff9f4b) Domain Event>> {
		Long especialistaId
		Long procedimentoId
		BigDecimal valor
		ComissaoId comissaoId
	}
	class ComissaoLiberada <<(E,#ff9f4b) Domain Event>> {
		Long especialistaId
		ComissaoId comissaoId
	}
}
package "'Repasse' Aggregate" <<Rectangle>> {
	class Repasse <<(A,#fffab8) Aggregate Root>> {
		Long especialistaId
		Long comissaoId
		Long procedimentoId
		Date dataPagamento
		BigDecimal valorRepassado
		Boolean estornado
		String justificativaEstorno
		RepasseId repasseId
	}
	class RepasseId <<(V,DarkSeaGreen) Value Object>> {
		Long id
	}
	class RepasseRegistrado <<(E,#ff9f4b) Domain Event>> {
		Long especialistaId
		BigDecimal valor
		Date dataPagamento
		RepasseId repasseId
	}
	class RepasseEstornado <<(E,#ff9f4b) Domain Event>> {
		Long especialistaId
		String justificativa
		RepasseId repasseId
	}
}
Repasse --> RepasseId : repasseId
ComissaoCalculada --> ComissaoId : comissaoId
Especialista --> EspecialistaId : especialistaId
RepasseRegistrado --> RepasseId : repasseId
EspecialistaCadastrado --> EspecialistaId : especialistaId
Comissao --> ComissaoId : comissaoId
RepasseEstornado --> RepasseId : repasseId
RegraComissao --> TipoComissao : tipo
Comissao --> StatusComissao : status
ComissaoLiberada --> ComissaoId : comissaoId
legend left
  This bounded context implements the subdomain 'EspecialistaDomain'.
end legend


@enduml
